version: "3.9"

volumes:
  data: {}

services:
  qqnt:
    build: .
    volumes:
      - data:/home/user/.config/QQ
    
    deploy:
      restart_policy:
        condition: on-failure

    ports:
      - "8083:8083"