#!/bin/bash -xve

X11VNC_PASSWORD_PATH=/etc/x11vnc.passwd
X11VNC_EXTRA_ARGS="-ncache 10 -noxdamage -noshared"
# if vnc password set, write password to file
if [ -n "$VNC_PASSWORD" ]; then
    x11vnc -storepasswd $VNC_PASSWORD $X11VNC_PASSWORD_PATH
    chmod 400 $X11VNC_PASSWORD_PATH
    X11VNC_EXTRA_ARGS="$X11VNC_EXTRA_ARGS -rfbauth $X11VNC_PASSWORD_PATH"
fi

x11vnc -display :0 $X11VNC_EXTRA_ARGS -forever -verbose